### ISSUE TITLE
 {a-chernousov] Локализация кнопок и текста

### ISSUE THREAD

**Issue by CNNOM** [CNNOM/Grafredactor_VSTU#1]
Сделать чтобы была поддержка русского и английского языка. Переключение через кнопку

**Comment by a-chernousov** [comment]
Чиназес

**Comment by CNNOM** [comment]
Не переименовывается поле с цветом

**Comment by CNNOM** [comment]
![IMG_20241210_130957_576.jpg](https://github.com/user-attachments/assets/781d7fc4-697e-43c4-82cf-63f9fe215423)
